# -*- coding: utf-8 -*-
"""Python Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oOeBZuvEx16JYyw9cekP9cnD5mJ5ucuG
"""

li = [int(i) for i in input("Enter the values: ").split()]

li.sort(reverse=True)
print(li)