# -*- coding: utf-8 -*-
"""Python Assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ggDRenCse-K3R5sFu7AtSLau74_K03R1
"""

li = [int(i) for i in input("Enter the values: ").split()]
x = int(input("Enter the element to be removed: "))

for i in li:
  if i == x:
    li.remove(x)
print(li)