# -*- coding: utf-8 -*-
"""Python Assignment 3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rTIcypwBOkPgMs_Irc5IC99zztVaEg6m
"""

import string

sen = input("Enter the sentence: ")
letters = string.ascii_lowercase

x = 0
for char in letters:
  if char not in sen.lower(): x = 1

if x == 1: print("The sentence is not a pangram")
else: print("The sentence is a pangram")
