# -*- coding: utf-8 -*-
"""Python Assignment 4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oWIJdFbZo9IgArxXmi02oGgLEuxHHbsx
"""

li = [6, 5, 4, 1, 2, 3]
new_li = []
x = 0
for i in range(1,len(person)+1):
  x = person.index(i)
  new_li.append(x+1)

print(li)
print(new_li)