# -*- coding: utf-8 -*-
"""Python Mini Project.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tBS2PeYRPbYeu3Yibl028tbvMaJ2XJ9u
"""

import random as rand
import string

length = int(input("Enetr the length of the OTP: "))
otp = ""
char = string.digits + string.ascii_letters

for i in range(length):
  otp += rand.choice(char)

print("OTP:", otp)