# -*- coding: utf-8 -*-
"""Temperature Conversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DpfJZL7bQjAs4YrVCtCiqUmrIHheh0DR
"""

c = int(input("Enter the temperature in celsius: "))
f = (c * 9/5) + 32
print("{}C is equal to {}F".format(c, f))